name: Hot Pink Site
favicon: null
layout_spectrum: 0.24713599146343768
typography_spectrum: 0.037338603753596544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f92b8f'
    - '#90f72a'
    - '#f8c52b'
    - '#90f829'
    - '#8ff72a'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
